name: flutter_blue_plus
description: Flutter plugin for connecting and communication with Bluetooth Low Energy devices, on Android and iOS
version: 1.5.4
homepage: https://github.com/boskokg/flutter_blue_plus

environment:
  sdk: ">=3.10.3 <4.0.0"
  flutter: ">=3.38.7"

dependencies:
  flutter:
    sdk: flutter
  convert: ^3.1.2
  protobuf: 5.1.0 # locked due to PbList ctr change in ^6+
  rxdart: ^0.28.0
  collection: ^1.19.1
  meta: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.boskokg.flutter_blue_plus
        pluginClass: FlutterBluePlusPlugin
      ios:
        pluginClass: FlutterBluePlusPlugin
